### ISSUE TITLE
第九回（Next.js）の Web フロントエンド開発における Node.js の必要性についての説明の補足

### ISSUE THREAD

**Issue by hmatsu47** [yoyoyo-pg/infra-study#4]
> - サーバーサイドJavaScript実行環境と呼ばれるものの、React.jsやVue.jsといったWebフロントエンドで利用されるのは何故？

という Q に対しての A、

> - React等を用いて大規模なアプリケーションを開発するとなると、様々なパッケージが必要で、各パッケージには依存関係があります。
> - Node.jsはパッケージのインストールと整合性を管理する為に必要で、npm（Node Package Manager）がその解決を担っています。
> - Javaの開発ではMavenやGradleといったビルドツールによるパッケージ管理をするので、それのJavaScript版だと理解して頂くと分かりやすいと思います。

について。

これは CSR only の Web フロントエンドではそのとおりなのですが、Next.js など SSR を実現するフレームワークを用いた開発では、加えて

- 開発環境におけるサーバー実行環境

としても必要ですね。

（もちろん CSR only の React 等でも、ブラウザ側の開発ツールと連動して開発体験の向上、例えば WebSocket 経由の通信を用いてホットモジュールリプレイスメント（HMR）などをするのにも使いますが）

なお最近では Deno や Bun など別の選択肢も増えてきています（が、当面デファクトスタンダードであり続けると思います）。

**Comment by yoyoyo-pg** [comment]
コメントありがとうございます！今回はNode.jsの紹介に主眼を置いていますが、

- Webフロントエンド観点だけでなく、サーバー実行環境である点
- ランタイムやエコシステムとして、様々な選択肢やツールがある点

辺りは記載しようかと思います！
